package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDisk<M extends BaseDisk<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setThumbImg(java.lang.String thumbImg) {
		set("thumbImg", thumbImg);
	}
	
	public java.lang.String getThumbImg() {
		return getStr("thumbImg");
	}

	
	public void setSize(java.lang.Long size) {
		set("size", size);
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setIsFolder(java.lang.Boolean isFolder) {
		set("isFolder", isFolder);
	}
	
	public java.lang.Boolean getIsFolder() {
		return get("isFolder");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public void setGmtModify(java.util.Date gmtModify) {
		set("gmtModify", gmtModify);
	}
	
	public java.util.Date getGmtModify() {
		return get("gmtModify");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

}
