package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setPkId(java.lang.Integer pkId) {
		set("pkId", pkId);
	}
	
	public java.lang.Integer getPkId() {
		return getInt("pkId");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setHtmlTitle(java.lang.String htmlTitle) {
		set("htmlTitle", htmlTitle);
	}
	
	public java.lang.String getHtmlTitle() {
		return getStr("htmlTitle");
	}

	public void setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public void setPv(java.lang.Integer pv) {
		set("pv", pv);
	}
	
	public java.lang.Integer getPv() {
		return getInt("pv");
	}

	public void setThumbImg(java.lang.String thumbImg) {
		set("thumbImg", thumbImg);
	}
	
	public java.lang.String getThumbImg() {
		return getStr("thumbImg");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setIsOriginal(java.lang.Integer isOriginal) {
		set("isOriginal", isOriginal);
	}
	
	public java.lang.Integer getIsOriginal() {
		return getInt("isOriginal");
	}

	public void setIsTop(java.lang.Integer isTop) {
		set("isTop", isTop);
	}
	
	public java.lang.Integer getIsTop() {
		return getInt("isTop");
	}

	public void setGmtModified(java.util.Date gmtModified) {
		set("gmtModified", gmtModified);
	}
	
	public java.util.Date getGmtModified() {
		return get("gmtModified");
	}

	public void setIdentify(java.lang.String identify) {
		set("identify", identify);
	}
	
	public java.lang.String getIdentify() {
		return getStr("identify");
	}

}
