package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKv<M extends BaseKv<M>> extends Model<M> implements IBean {

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	
	public void setK(java.lang.String k) {
		set("k", k);
	}
	
	public java.lang.String getK() {
		return getStr("k");
	}

	public void setV(java.lang.String v) {
		set("v", v);
	}
	
	public java.lang.String getV() {
		return getStr("v");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

}
