package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHtmlAction<M extends BaseHtmlAction<M>> extends Model<M> implements IBean {

	public M setPkId(java.lang.Long pkId) {
		set("pkId", pkId);
		return (M)this;
	}
	
	public java.lang.Long getPkId() {
		return getLong("pkId");
	}

	public M setPath(java.lang.String path) {
		set("path", path);
		return (M)this;
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}

	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}
	
	public java.lang.String getAction() {
		return getStr("action");
	}

}
