package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseKv<M extends BaseKv<M>> extends Model<M> implements IBean {

	public M setK(java.lang.String k) {
		set("k", k);
		return (M)this;
	}
	
	public java.lang.String getK() {
		return getStr("k");
	}

	public M setV(java.lang.String v) {
		set("v", v);
		return (M)this;
	}
	
	public java.lang.String getV() {
		return getStr("v");
	}

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
