package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCodeRelMeta<M extends BaseCodeRelMeta<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setModityCodeId(java.lang.Integer modityCodeId) {
		set("modityCodeId", modityCodeId);
		return (M)this;
	}
	
	public java.lang.Integer getModityCodeId() {
		return getInt("modityCodeId");
	}

	public M setMetaId(java.lang.Integer metaId) {
		set("metaId", metaId);
		return (M)this;
	}
	
	public java.lang.Integer getMetaId() {
		return getInt("metaId");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

}
