package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRelevancy<M extends BaseRelevancy<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setMid(java.lang.Integer mid) {
		set("mid", mid);
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}
	
	public java.lang.Integer getCid() {
		return getInt("cid");
	}

}
