package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAccessLog<M extends BaseAccessLog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmtCreate", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmtCreate");
	}

	public M setReferer(java.lang.String referer) {
		set("referer", referer);
		return (M)this;
	}
	
	public java.lang.String getReferer() {
		return getStr("referer");
	}

	public M setTarget(java.lang.String target) {
		set("target", target);
		return (M)this;
	}
	
	public java.lang.String getTarget() {
		return getStr("target");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}
	
	public java.lang.String getIp() {
		return getStr("ip");
	}

	public M setCookie(java.lang.String cookie) {
		set("cookie", cookie);
		return (M)this;
	}
	
	public java.lang.String getCookie() {
		return getStr("cookie");
	}

	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public M setUserAgent(java.lang.String userAgent) {
		set("userAgent", userAgent);
		return (M)this;
	}
	
	public java.lang.String getUserAgent() {
		return getStr("userAgent");
	}

}
