package com.wenhaofan.common.model.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlogroll<M extends BaseBlogroll<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setUkPriority(java.lang.Integer ukPriority) {
		set("ukPriority", ukPriority);
		return (M)this;
	}
	
	public java.lang.Integer getUkPriority() {
		return getInt("ukPriority");
	}

	public M setUkName(java.lang.String ukName) {
		set("ukName", ukName);
		return (M)this;
	}
	
	public java.lang.String getUkName() {
		return getStr("ukName");
	}

	public M setUkUrl(java.lang.String ukUrl) {
		set("ukUrl", ukUrl);
		return (M)this;
	}
	
	public java.lang.String getUkUrl() {
		return getStr("ukUrl");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
