package com.wenhaofan.common.model.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "pkId", Article.class);
		arp.addMapping("blogroll", "pkId", Blogroll.class);
		arp.addMapping("login_record", "pkId", LoginRecord.class);
		arp.addMapping("user", "pkId", User.class);
		arp.addMapping("session", "id", Session.class);	
		arp.addMapping("html_action","pkId", HtmlAction.class);
		arp.addMapping("meta", "id",Meta.class);
		arp.addMapping("relevancy","id",Relevancy.class);
		arp.addMapping("kv", "id",Kv.class);
		arp.addMapping("access_log", "id", AccessLog.class);
		arp.addMapping("disk", "id", Disk.class);
		arp.addMapping("agent_user", "id", AgentUser.class);
		arp.addMapping("comment", "id", Comment.class);
	}

	 
}