package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseAccessLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccessLog extends BaseAccessLog<AccessLog> {
	
}
