package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {

	public static Integer STATE_DRAFT=0;
	public static Integer STATE_PUBLISH=1;
	public static Integer STATE_DISCARD=2;
	
}
