package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseBaiduSeoConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaiduSeoConfig extends BaseBaiduSeoConfig<BaiduSeoConfig> {
	
}
