package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	
}
