package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseBasicConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseBasicConfig<Config> {
	
}
