package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseDisk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Disk extends BaseDisk<Disk> {
	
}
