package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseKv;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kv extends BaseKv<Kv> {
	
}
