package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseMetaweblogConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MetaweblogConfig extends BaseMetaweblogConfig<MetaweblogConfig> {
	
}
