package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseMeta;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Meta extends BaseMeta<Meta> {
	
}
