package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseNav;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Nav extends BaseNav<Nav> {
	
}
