package com.wenhaofan.common.model.entity;

import com.wenhaofan.common.model.entity.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	
}
