package tpl.com.wenhaofan.common.model;

import tpl.com.wenhaofan.common.model.base.BaseArticle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	
}
