package tpl.com.wenhaofan.common.model;

import tpl.com.wenhaofan.common.model.base.BaseComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comment extends BaseComment<Comment> {
	
}
