package tpl.com.wenhaofan.common.model;

import tpl.com.wenhaofan.common.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	
}
