package tpl.com.wenhaofan.common.model;

import tpl.com.wenhaofan.common.model.base.BaseMetaweblogRelevance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MetaweblogRelevance extends BaseMetaweblogRelevance<MetaweblogRelevance> {
	
}
